### ISSUE TITLE
In "At at glance" the second column "New"  between "Total" and "Recovered" should be per capita new.

### ISSUE THREAD

**Issue by windbender** [xunhuang/covid-19#141]
Total is a nice number for news articles but because the numbers are not per capita it's difficult to compare two different areas which do not have the same population.

This column should be split into  "new per capita"  or perhaps "new per 100k"

And then the the other side of the split should be "growth"  so you can sort by daily % growth rate.

**Comment by xunhuang** [comment]
The daily graph is meant to report total. Since it's showing data from one single location per capita or not it doesn't matter. Comparing is more difficult but that's not the point of that graph. :)

As such, I created a new graph for comparing data of county, to its metro, state, and US. 

https://covid-19.direct/county/CA/Santa%20Clara?tab=compare 

Hope that helps.
