### ISSUE TITLE
Map issues

### ISSUE THREAD

**Issue by xunhuang** [xunhuang/covid-19#71]
Hi April,

I experimented a bit with the Map today with state and here are some issues that I found: 

1) I did a quick hack to load the state map, perf is slow to load because it's loading county tiles from the entire country. Should be easy fix. 
2) I wish on desktop tooltips auto pop up with the having the click on it. 
3) I wish tooltips contents can be arbitrary, including buttons that user can click. 
4) Placement of tooltip are suboptimal around edges. 
5) zoom is interfacing with scrolling, wish there is a way to turn it off. 
6) strange bug, if you click on the Map tap, and then click away to another tab, something in the map crashes. 

Obviously this might represent a lot fixes. 
Have you seen https://www.react-simple-maps.io/examples/map-chart-with-tooltip/? do you have any thoughts on whether we should fix the problems of current maps, or see if the other one is legit? (I'm pretty sure we will run into other types of issues with the other one too.)
 
I checked in changes for the map that you can check out in PageState.js

![image](https://user-images.githubusercontent.com/729879/78617564-990ece80-782c-11ea-83b7-b2c83aab284f.png)

**Comment by xunhuang** [comment]
cc: @aschleck  to get your attention.

**Comment by aschleck** [comment]
Thanks for taking a look! I'm a bit invested at this point so I, perhaps a victim of the sunk cost fallacy, would like to take a stab at fixing these issues. That other map does look quite legit, but it doesn't seem to support the eg Safari gestures API so pinch zoom is broken when used that way. I also wonder about its performance as the number of things scales up, though I recognize that mine also struggles there.

I think if you wanted to make an executive decision and say we should use that I would accept it, but otherwise I'm happy to throw time at this.

**Comment by xunhuang** [comment]
thank you April, let me play with it tonight and get a feel for it. formats
are in topojson and if I understand correctly they contain geo reference so
polygons supposedly can be overlaid on a real map. I did find the topojson
for state counties here:

https://github.com/deldersveld/topojson/blob/master/countries/us-states

Please don't sink more time into this issue until I evaluated it.

**Comment by aschleck** [comment]
It's interesting, that map implementation "side stepped" something that caused me to avoid other typical zoom/pan components when I looked around before starting. The other ones I found were fine, but when zooming in the tooltip would scale up too. So I ended up writing something that didn't cause the tooltip to scale while changing.

This one just puts the tooltip wherever the user's mouse is, which seems to work well on desktop. And it means that you can't render a static tooltip, but their desktop UX doesn't require that (since they just show labels where the user's mouse is.) But it's pretty broken on mobile, at least on my phone you tap to get the tooltip to show up but then you can pan and the tooltip detaches from reality.

**Comment by xunhuang** [comment]
I put the map in a few things that I notice: 

1) it loads fast. I think it doesn't try to precompute the tooltip content and stick into map. 
2) mouse over experience is great on desktop. On mobile is ok too as long as you don't zoom. If you zoom, the tooltip seems to show in off/places. 
3) it has the same edge issue as our current implementation.
4)  panning also interfere with scrolling.
5) Certainly not good taste for color as yours! 

Still playing with it.  

![image](https://user-images.githubusercontent.com/729879/78628382-d7b28200-7848-11ea-943c-a18f1fde903d.png)

**Comment by aschleck** [comment]
I'm thinking you're right that panning and zooming is a bad idea when embedded in a pre-existing page like this. I am playing around with refactoring what I did to make it optional.

I do feel like there's good UX to be had around making a map view with gestures, but it probably requires doing something like [Bing did](https://www.bing.com/covid/local/unitedstates) where you make the map the focal point rather than expecting scrolling to work. Something I want to try is making a view where you can zoom in from the Bing style country view into a county level view, I have some ideas on how to do it but I think the performance might end up being terrible.

**Comment by xunhuang** [comment]
for the new map, they have to add a React.memo( xxx) to wrap around the country to make it less flicker to improve perf. 

below looks familiar. :)
 
![image](https://user-images.githubusercontent.com/729879/78629397-ccad2100-784b-11ea-81b9-c70423e523ce.png)

**Comment by xunhuang** [comment]
@aschleck , do you understand how these projection stuff work? Since you slice the old county maps up, you probably know. this new package just use projection="geoAlbersUsa" and called it a day and I'm kinda stuck.

**Comment by aschleck** [comment]
Haha, I spent yesterday learning about the projections from this book: https://pubs.usgs.gov/bul/1532/report.pdf. What do you want to know? Feel free to message over FB if that's easier.

**Comment by xunhuang** [comment]
https://covid-19.direct/state/NY?graph=map 
I need to make this NY map centered. :( 

(sent you a friend request, but working on homework with my kid right now. )
